name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a9f13900c6b04073aa678909ca55b80150c22cb339d37bcea49978b9cc0154f"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
