name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e950a4f6decf3595cdb84281e9e278649a18dc4b74eb5143b62e35d71ca4626"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
