name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79e552d89fb298b0a7f894a00e93a18dc782e3528b37592ede72e7cf349e6fd2"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
