name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b14908463aa09344f7b9f6d639dc110ff9ca5472e27369d32fa3db1f98558cf"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
