name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6035c610aac0f354ffae0940562e812ec7f3a3def7bc10bffd97050c1417b737"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
