name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cff997de5e488320afab8f30d598930a50dc4d931912ab1bb65921b5f9a0807"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
