name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ab438992a60df946146504450a1270633a0c615663a3f24243ffb6aff570b3"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
