name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e29be9b773613c9cf24dc6eb7bbf7934483ee64cd67136726f55c3b280e2770f"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
