name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7387cec00850add2f09c2037ff33f5f060275247c8ee583233fccca07257dba6"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
