name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c5d1e00f3503eeece9e1d01cc485ba44c59e3587431cf581c1e2ce84a628f96"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
