name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23eb9b0ed821886651950b3d0ae2e9db9d6924d73348678ed75a693f62044a0f"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
