name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b379455c35f0fcaacd5295d2424e1e094bb0a6070aa59f2ebf8a270b2b0b015"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
