name = "USTCreate REBUILD"
author = "XeF2,miaoning-exe,rrtt217"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9794dd6f5716bb31a05a48c27c33e28b828a7fdfcbb2f2fc030a67e15a343aa7"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
